name: Git Cliff action
description:  Generate Changelog with a customized template 
author: tj-actions
inputs:
  args:
    description: "Extra args passed directly to [git-cliff](https://github.com/orhun/git-cliff#command-line-arguments)"
    required: false
    default: "--verbose"
  output:
    description: "Output file"
    required: false
    default: "HISTORY.md"
  template-config:
    description: "Path or URL to the template `cliff.toml` config file. See [`cliff-template.toml`](./cliff-template.toml) for a working example. **NOTE:** Only the `REPOSITORY_URL` is substituted."
    required: false

runs:
  using: 'composite'
  steps:
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: git-cliff
      shell: bash
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs
        INPUT_REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
        INPUT_TEMPLATE_CONFIG: ${{ inputs.template-config }}

    - name: Setup bin
      uses: tj-actions/setup-bin@v1
      id: setup-bin-rust
      with:
        repository-owner: orhun
        repository: git-cliff
        version: latest
        language-type: 'rust'

    - name: Generate a changelog
      shell: bash
      run: |
        ${{ steps.setup-bin-rust.outputs.binary_path }} ${{ inputs.args }} --config ${{ steps.git-cliff.outputs.output_path }}
      env:
        GIT_CLIFF_OUTPUT: ${{ inputs.output }}
        
    - name: Cleanup
      shell: bash
      run: |
        bash $GITHUB_ACTION_PATH/cleanup.sh
      env:
        INPUT_OUTPUT_PATH: ${{ steps.git-cliff.outputs.output_path }}
branding:
  icon: check-square
  color: white
