name: Git Cliff action
description:  Generate Changelog with a customized template 
author: tj-actions
inputs:
  args:
    description: "Extra args passed directly to [git-cliff](https://github.com/orhun/git-cliff#command-line-arguments)"
    required: false
    default: "--verbose"
  output:
    description: "Output file"
    required: false
    default: "HISTORY.md"

runs:
  using: 'composite'
  steps:
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: git-cliff
      shell: bash
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs
        INPUT_REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}

    - name: Generate a changelog
      uses: orhun/git-cliff-action@v2
      with:
        config: ${{ steps.git-cliff.outputs.output_path }}
        args: ${{ inputs.args }}
      env:
        OUTPUT: ${{ inputs.output }}
        
    - name: Cleanup
      shell: bash
      run: |
        bash $GITHUB_ACTION_PATH/cleanup.sh
      env:
        INPUT_OUTPUT_PATH: ${{ steps.git-cliff.outputs.output_path }}
branding:
  icon: check-square
  color: white
