name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1

  test:
    name: Test git-cliff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0

      - name: Run git-cliff
        uses: ./
        
      - name: Run git-cliff with a URL based template
        uses: ./
        with:
          template-config: "https://raw.githubusercontent.com/tj-actions/git-cliff/main/cliff-template.toml"
